"""midia

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-16 20:22:57.338070
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0003'
down_revision: str | None = '0002'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('midia',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('hash_sha256', sa.String(length=64), nullable=False),
    sa.Column('tipo_mime', sa.String(length=100), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('resultado', sa.Text(), nullable=False),
    sa.Column('metadados', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_midia_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_midia')),
    sa.UniqueConstraint('cliente_id', 'hash_sha256', name=op.f('uq_midia_cliente_id'))
    )
    op.create_index(op.f('ix_midia_cliente_id'), 'midia', ['cliente_id'], unique=False)
    op.add_column('mensagem', sa.Column('anexo', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('mensagem', sa.Column('midia_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(op.f('fk_mensagem_midia_id_midia'), 'mensagem', 'midia', ['midia_id'], ['id'])
    op.add_column('turno', sa.Column('funcao', sa.String(length=20), server_default='resposta', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turno', 'funcao')
    op.drop_constraint(op.f('fk_mensagem_midia_id_midia'), 'mensagem', type_='foreignkey')
    op.drop_column('mensagem', 'midia_id')
    op.drop_column('mensagem', 'anexo')
    op.drop_index(op.f('ix_midia_cliente_id'), table_name='midia')
    op.drop_table('midia')
    # ### end Alembic commands ###
