"""handoff

Revision ID: 0005
Revises: 0004
Create Date: 2026-09-16 21:05:08.930551
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0005'
down_revision: str | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handoff',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('agente_id', sa.Uuid(), nullable=False),
    sa.Column('conversa_id', sa.Uuid(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('resumo', sa.Text(), nullable=False),
    sa.Column('codigo', sa.String(length=12), nullable=False),
    sa.Column('destino', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('iniciado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('retomar_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retomado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retomado_por', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agente.id'], name=op.f('fk_handoff_agente_id_agente')),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_handoff_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], name=op.f('fk_handoff_conversa_id_conversa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handoff')),
    sa.UniqueConstraint('agente_id', 'codigo', name=op.f('uq_handoff_agente_id'))
    )
    op.create_index(op.f('ix_handoff_cliente_id'), 'handoff', ['cliente_id'], unique=False)
    op.create_index('uq_handoff_conversa_aberto', 'handoff', ['conversa_id'], unique=True, postgresql_where='retomado_em IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_handoff_conversa_aberto', table_name='handoff', postgresql_where='retomado_em IS NULL')
    op.drop_index(op.f('ix_handoff_cliente_id'), table_name='handoff')
    op.drop_table('handoff')
    # ### end Alembic commands ###
