"""digitacao e ferramentas do agente

Revision ID: 0007
Revises: 0006
Create Date: 2026-09-16 23:22:56.627781
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0007'
down_revision: str | None = '0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agente', sa.Column('digitacao_caracteres_por_segundo', sa.Integer(), server_default='6', nullable=False))
    op.add_column('agente', sa.Column('digitacao_maximo_segundos', sa.Integer(), server_default='20', nullable=False))
    op.add_column('agente', sa.Column('ferramentas', postgresql.JSONB(astext_type=sa.Text()), server_default='["calculadora", "busca_web"]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agente', 'ferramentas')
    op.drop_column('agente', 'digitacao_maximo_segundos')
    op.drop_column('agente', 'digitacao_caracteres_por_segundo')
    # ### end Alembic commands ###
