"""schema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-16 18:01:21.206476
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('removido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cliente')),
    sa.UniqueConstraint('slug', name=op.f('uq_cliente_slug'))
    )
    op.create_table('agente',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('credenciais_cifradas', sa.Text(), nullable=False),
    sa.Column('token_webhook_hash', sa.String(length=64), nullable=False),
    sa.Column('token_webhook_cifrado', sa.Text(), nullable=False),
    sa.Column('arquivo_prompt', sa.String(length=500), nullable=False),
    sa.Column('arquivo_prompt_handoff', sa.String(length=500), nullable=False),
    sa.Column('modelo_conversa', sa.String(length=100), nullable=False),
    sa.Column('modelo_auxiliar', sa.String(length=100), nullable=False),
    sa.Column('modelo_visao', sa.String(length=100), nullable=False),
    sa.Column('modelo_transcricao', sa.String(length=100), nullable=False),
    sa.Column('buffer_segundos', sa.Integer(), nullable=False),
    sa.Column('max_mensagens_por_resposta', sa.Integer(), nullable=False),
    sa.Column('handoff_destino', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('handoff_template', sa.String(length=200), nullable=True),
    sa.Column('retomada_automatica_horas', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('removido_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_agente_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agente')),
    sa.UniqueConstraint('cliente_id', 'slug', name=op.f('uq_agente_cliente_id')),
    sa.UniqueConstraint('token_webhook_hash', name=op.f('uq_agente_token_webhook_hash'))
    )
    op.create_index(op.f('ix_agente_cliente_id'), 'agente', ['cliente_id'], unique=False)
    op.create_table('contato',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('agente_id', sa.Uuid(), nullable=False),
    sa.Column('id_externo', sa.String(length=200), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=50), nullable=True),
    sa.Column('ultima_mensagem_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agente.id'], name=op.f('fk_contato_agente_id_agente')),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_contato_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contato')),
    sa.UniqueConstraint('agente_id', 'id_externo', name=op.f('uq_contato_agente_id'))
    )
    op.create_index(op.f('ix_contato_cliente_id'), 'contato', ['cliente_id'], unique=False)
    op.create_table('falha',
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('agente_id', sa.Uuid(), nullable=True),
    sa.Column('tipo', sa.String(length=100), nullable=False),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agente.id'], name=op.f('fk_falha_agente_id_agente')),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_falha_cliente_id_cliente')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_falha'))
    )
    op.create_index(op.f('ix_falha_cliente_id'), 'falha', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_falha_tipo'), 'falha', ['tipo'], unique=False)
    op.create_table('conversa',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('agente_id', sa.Uuid(), nullable=False),
    sa.Column('contato_id', sa.Uuid(), nullable=False),
    sa.Column('id_externo', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agente_id'], ['agente.id'], name=op.f('fk_conversa_agente_id_agente')),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_conversa_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['contato_id'], ['contato.id'], name=op.f('fk_conversa_contato_id_contato')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversa')),
    sa.UniqueConstraint('agente_id', 'id_externo', name=op.f('uq_conversa_agente_id'))
    )
    op.create_index(op.f('ix_conversa_cliente_id'), 'conversa', ['cliente_id'], unique=False)
    op.create_table('mensagem',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('conversa_id', sa.Uuid(), nullable=False),
    sa.Column('direcao', sa.String(length=10), nullable=False),
    sa.Column('autor', sa.String(length=10), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('texto_extraido', sa.Text(), nullable=True),
    sa.Column('id_externo', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_mensagem_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], name=op.f('fk_mensagem_conversa_id_conversa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mensagem'))
    )
    op.create_index(op.f('ix_mensagem_cliente_id'), 'mensagem', ['cliente_id'], unique=False)
    op.create_index('ix_mensagem_conversa_criado', 'mensagem', ['conversa_id', 'criado_em'], unique=False)
    op.create_index('uq_mensagem_conversa_id_externo', 'mensagem', ['conversa_id', 'id_externo'], unique=True, postgresql_where='id_externo IS NOT NULL')
    op.create_table('turno',
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('conversa_id', sa.Uuid(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('tokens_entrada', sa.Integer(), nullable=False),
    sa.Column('tokens_saida', sa.Integer(), nullable=False),
    sa.Column('custo_estimado', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('latencia_ms', sa.Integer(), nullable=False),
    sa.Column('tools_chamadas', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('erro', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], name=op.f('fk_turno_cliente_id_cliente')),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa.id'], name=op.f('fk_turno_conversa_id_conversa')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_turno'))
    )
    op.create_index(op.f('ix_turno_cliente_id'), 'turno', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_turno_conversa_id'), 'turno', ['conversa_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turno_conversa_id'), table_name='turno')
    op.drop_index(op.f('ix_turno_cliente_id'), table_name='turno')
    op.drop_table('turno')
    op.drop_index('uq_mensagem_conversa_id_externo', table_name='mensagem', postgresql_where='id_externo IS NOT NULL')
    op.drop_index('ix_mensagem_conversa_criado', table_name='mensagem')
    op.drop_index(op.f('ix_mensagem_cliente_id'), table_name='mensagem')
    op.drop_table('mensagem')
    op.drop_index(op.f('ix_conversa_cliente_id'), table_name='conversa')
    op.drop_table('conversa')
    op.drop_index(op.f('ix_falha_tipo'), table_name='falha')
    op.drop_index(op.f('ix_falha_cliente_id'), table_name='falha')
    op.drop_table('falha')
    op.drop_index(op.f('ix_contato_cliente_id'), table_name='contato')
    op.drop_table('contato')
    op.drop_index(op.f('ix_agente_cliente_id'), table_name='agente')
    op.drop_table('agente')
    op.drop_table('cliente')
    # ### end Alembic commands ###
