"""acesso do operador ao canal

Revision ID: 0006
Revises: 0005
Create Date: 2026-09-16 22:24:51.051279
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '0006'
down_revision: str | None = '0005'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acesso_canal',
    sa.Column('canal', sa.String(length=20), nullable=False),
    sa.Column('endereco', sa.String(length=500), nullable=False),
    sa.Column('acesso_cifrado', sa.Text(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_acesso_canal')),
    sa.UniqueConstraint('canal', 'endereco', name=op.f('uq_acesso_canal_canal'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acesso_canal')
    # ### end Alembic commands ###
